### PR TITLE
feat(ui/info): add verion, resource and contact information to application

### PR DESCRIPTION
**Pull request by ChrisRousey**
This PR introduces some static information to our application.
A Footer has beed added to the main layout (it will be contained on each page of the application), with three categories for the user to choose from. Upon clicking them, the related information is shown via a dropdown.

Bildschirmfoto 2023-05-11 um 17 54 28
Bildschirmfoto 2023-05-11 um 17 54 37
Bildschirmfoto 2023-05-11 um 17 54 46
Bildschirmfoto 2023-05-11 um 17 55 00

### CODE REVIEW

**Comment by ChrisRousey** [comment]
@flippingbits @HknLof @olis1996 

Hey team,

I would be happy to get some feedback on the information footer i have added. One thing i couldn't figure out is the state management inside the footer when soomething happens inside another component. I would like the footer to be reset when a user opens a different subpage. Any tips?

**Comment by flippingbits** [comment]
Thanks a lot for your work on this open issue!

I just checked out the PR branch and played a bit with the UI. Unfortunately, in some cases, the footer messes with the existing layout, e.g., in our pipeline designer.

I still like the idea of having the version information available in the UI. What do you think about introducing an "info" icon to the main navigation, which opens a dropdown showing the version information when being clicked?

I just played with an example from the Bootstrap documentation:

Screenshot 2023-05-12 at 08 59 15
Screenshot 2023-05-12 at 08 59 18

You can reproduce this behavior by applying the following diff to the file `/ui/src/components/layout/Navigation.js`:

```js
@@ -5,6 +5,7 @@ import {
   Book,
   Code,
   Home,
+  Info,
   Mail,
   LogOut,
   PlayCircle,
@@ -108,12 +109,46 @@ class Navigation extends Component {
             <div className="my-2 my-md-0">
               <a
                 href="/sign_out/"
-                className="nav-link"
+                className="nav-link float-end ms-4"
                 onClick={this.handleSignOut}
               >
-                <LogOut className="feather-icon" />{" "}
-                <span className="ms-1">Sign out</span>
+                <LogOut className="feather-icon" /> <span>Sign out</span>
               </a>
+              <div className="dropdown float-end">
+                <a
+                  href="#"
+                  className="link-dark text-decoration-none dropdown-toggle"
+                  data-bs-toggle="dropdown"
+                  aria-expanded="false"
+                >
+                  <Info className="feather-icon" />
+                </a>
+                <ul className="dropdown-menu text-small">
+                  <li>
+                    <a className="dropdown-item" href="#">
+                      This is dummy content
+                    </a>
+                  </li>
+                  <li>
+                    <a className="dropdown-item" href="#">
+                      that needs to be filled
+                    </a>
+                  </li>
+                  <li>
+                    <a className="dropdown-item" href="#">
+                      with smth meaningful.
+                    </a>
+                  </li>
+                  <li>
+                    <hr className="dropdown-divider" />
+                  </li>
+                  <li>
+                    <a className="dropdown-item" href="#">
+                      OK?
+                    </a>
+                  </li>
+                </ul>
+              </div>
             </div>
           </div>
         </div>
```

I look forward to your feedback and please let me know if I can be of help.

**Comment by ChrisRousey** [comment]
Thanks for your feedback @flippingbits 

I implemented the changes and agree, it looks much better. i only added the version info here to avoid it beeing too cluttered.

Bildschirmfoto 2023-05-19 um 13 26 27

**Comment by flippingbits** [comment]
Thanks for the update, looks great!

I added two small changes to improve the rendering of the version info:

* When the version information is unavailable, do not render the dropdown (previously the entire navigation has not been rendered).
* Re-render navigation when switching pages, so the active navigation item is being updated.

**Review by flippingbits — APPROVED** [review]

**Pull request merged**
